# Bossting Algoerithm:

In [2]:
# import libraries is basic and using in Boosting Algoerithm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score, confusion_matrix, classification_report
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from  sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder

In [3]:
# load the 'iris' dataset:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
# split the dataset X and y:

X = df.drop('species', axis=1)
y = df['species']

In [5]:
# encode the target variable:
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
# split the train and test data:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [7]:
# train the decision tree model:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [8]:
# predict the test data:
y_pred = model.predict(X_test)

# Evaluate the model:
print('Accuracy_score:', accuracy_score(y_test, y_pred))        
print('precision_score:', metrics.precision_score(y_test, y_pred, average='macro'))
print('recall_score:', metrics.recall_score(y_test, y_pred, average='macro'))
print('f1_score:', metrics.f1_score(y_test, y_pred, average='macro'))

Accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
f1_score: 1.0

In [9]:
# train the random forest model:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train) 

# evaluate the model:
y_pred = model.predict(X_test)
print('Accuracy_score:', accuracy_score(y_test, y_pred))        
print('precision_score:', metrics.precision_score(y_test, y_pred, average='macro'))
print('recall_score:', metrics.recall_score(y_test, y_pred, average='macro'))
print('f1_score:', metrics.f1_score(y_test, y_pred, average='macro'))

Accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
f1_score: 1.0

In [10]:
# train the xgboost model:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

# predicte the test data:
y_pred = xgb.predict(X_test)

# Evaluate the model:
print('Accuracy_score:', accuracy_score(y_test, y_pred))        
print('precision_score:', metrics.precision_score(y_test, y_pred, average='macro'))
print('recall_score:', metrics.recall_score(y_test, y_pred, average='macro'))
print('f1_score:', metrics.f1_score(y_test, y_pred, average='macro'))

Accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
f1_score: 1.0

In [11]:
# import the of recall and f1_score library
from sklearn.metrics import recall_score, f1_score

In [12]:
# make the bar  plot showing each of the matrix with respect to the model:
from matplotlib import pyplot as plt

---

# CatBoost Algoorithm:

In [14]:
#  import libreries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score, confusion_matrix, classification_report
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from  sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from catboost import CatBoostRegressor

In [15]:
# load the 'titanic' dataset:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
# prepprocessing the data:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
# imput the missing values in age and fare:
df['age'].fillna(df['age'].median(), inplace=True)
df['fare'].fillna(df['fare'].median(), inplace=True)
df['deck'].fillna('C', inplace=True)
# impute the missing values in embarked and embark_town:
df['embarked'].fillna('S', inplace=True)
df['embark_town'].fillna('Southampton', inplace=True)
df.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16788\1618878204.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16788\1618878204.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fare'].fillna(df['fare'].median(), inplace=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16788\1618878204.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['deck'].fillna('C', inplace=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16788\1618878204.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna('S', inplace=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_16788\1618878204.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embark_town'].fillna('Southampton', inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True

In [18]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [19]:
#  convert the category columns to category:
category_col = df.select_dtypes(include=['object','category']).columns

# add this a new column in the dataframe:
df[category_col] = df[category_col].astype('category')

In [20]:
# split the data into X and y:
X = df.drop('survived', axis=1)
y = df['survived']

# split the data into train and test:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [21]:
# run the catboost classfier:
model = CatBoostRegressor(iterations=1000, 
                           learning_rate=0.1,
                           depth=3,
                           loss_function='RMSE',
                           random_seed=42,
                           eval_metric='RMSE')

In [ ]:
#  train the model:
model.fit(X_train, y_train,cat_features=category_col.tolist()) 

# predict the test data:
y_pred = model.predict(X_test)
# evaluate the model:
        
print('confusion_matrix:', confusion_matrix(y_test, y_pred))
print('classification_report:', classification_report(y_test, y_pred))

0:	learn: 0.4375060	total: 316ms	remaining: 5m 15s
1:	learn: 0.3953073	total: 349ms	remaining: 2m 54s
2:	learn: 0.3561524	total: 388ms	remaining: 2m 8s
3:	learn: 0.3208763	total: 414ms	remaining: 1m 43s
4:	learn: 0.2896759	total: 461ms	remaining: 1m 31s
5:	learn: 0.2613540	total: 499ms	remaining: 1m 22s
6:	learn: 0.2360941	total: 540ms	remaining: 1m 16s
7:	learn: 0.2131452	total: 565ms	remaining: 1m 10s
8:	learn: 0.1922367	total: 586ms	remaining: 1m 4s
9:	learn: 0.1735937	total: 597ms	remaining: 59.1s
10:	learn: 0.1568731	total: 611ms	remaining: 54.9s
11:	learn: 0.1413478	total: 621ms	remaining: 51.1s
12:	learn: 0.1276907	total: 642ms	remaining: 48.7s
13:	learn: 0.1152776	total: 658ms	remaining: 46.3s
14:	learn: 0.1041082	total: 672ms	remaining: 44.1s
15:	learn: 0.0940942	total: 687ms	remaining: 42.3s
16:	learn: 0.0850476	total: 702ms	remaining: 40.6s
17:	learn: 0.0767497	total: 718ms	remaining: 39.2s
18:	learn: 0.0692497	total: 734ms	remaining: 37.9s
19:	learn: 0.0625697	total: 751ms	remaining: 36.8s
20:	learn: 0.0565374	total: 768ms	remaining: 35.8s
21:	learn: 0.0511311	total: 783ms	remaining: 34.8s
22:	learn: 0.0462494	total: 798ms	remaining: 33.9s
23:	learn: 0.0418430	total: 813ms	remaining: 33.1s
24:	learn: 0.0378515	total: 827ms	remaining: 32.2s
25:	learn: 0.0342246	total: 842ms	remaining: 31.6s
26:	learn: 0.0309889	total: 865ms	remaining: 31.2s
27:	learn: 0.0280704	total: 879ms	remaining: 30.5s
28:	learn: 0.0254459	total: 897ms	remaining: 30s
29:	learn: 0.0230769	total: 913ms	remaining: 29.5s
30:	learn: 0.0209044	total: 927ms	remaining: 29s
31:	learn: 0.0189718	total: 941ms	remaining: 28.5s
32:	learn: 0.0172278	total: 968ms	remaining: 28.4s
33:	learn: 0.0156744	total: 989ms	remaining: 28.1s
34:	learn: 0.0142606	total: 1s	remaining: 27.6s
35:	learn: 0.0130072	total: 1.02s	remaining: 27.3s
36:	learn: 0.0118719	total: 1.03s	remaining: 26.9s
37:	learn: 0.0108797	total: 1.06s	remaining: 26.9s
38:	learn: 0.0099878	total: 1.08s	remaining: 26.6s
39:	learn: 0.0092075	total: 1.13s	remaining: 27.1s
40:	learn: 0.0085221	total: 1.15s	remaining: 26.9s
41:	learn: 0.0078926	total: 1.17s	remaining: 26.7s
42:	learn: 0.0072849	total: 1.2s	remaining: 26.6s
43:	learn: 0.0067786	total: 1.21s	remaining: 26.3s
44:	learn: 0.0062803	total: 1.23s	remaining: 26.1s
45:	learn: 0.0058747	total: 1.25s	remaining: 25.8s
46:	learn: 0.0055066	total: 1.26s	remaining: 25.6s
47:	learn: 0.0052028	total: 1.27s	remaining: 25.3s
48:	learn: 0.0049264	total: 1.29s	remaining: 25s
49:	learn: 0.0046355	total: 1.31s	remaining: 24.8s
50:	learn: 0.0043700	total: 1.33s	remaining: 24.8s
51:	learn: 0.0041298	total: 1.35s	remaining: 24.6s
52:	learn: 0.0039554	total: 1.36s	remaining: 24.4s
53:	learn: 0.0037852	total: 1.38s	remaining: 24.2s
54:	learn: 0.0036092	total: 1.4s	remaining: 24s
55:	learn: 0.0034649	total: 1.41s	remaining: 23.8s
56:	learn: 0.0033257	total: 1.43s	remaining: 23.7s
57:	learn: 0.0032190	total: 1.45s	remaining: 23.5s
58:	learn: 0.0031069	total: 1.46s	remaining: 23.3s
59:	learn: 0.0030084	total: 1.48s	remaining: 23.1s
60:	learn: 0.0029436	total: 1.49s	remaining: 23s
61:	learn: 0.0028896	total: 1.51s	remaining: 22.8s
62:	learn: 0.0028318	total: 1.52s	remaining: 22.6s
63:	learn: 0.0028212	total: 1.54s	remaining: 22.5s
64:	learn: 0.0027705	total: 1.55s	remaining: 22.3s
65:	learn: 0.0027518	total: 1.57s	remaining: 22.3s
66:	learn: 0.0027074	total: 1.59s	remaining: 22.2s
67:	learn: 0.0026810	total: 1.61s	remaining: 22s
68:	learn: 0.0026687	total: 1.62s	remaining: 21.9s
69:	learn: 0.0026607	total: 1.64s	remaining: 21.7s
70:	learn: 0.0026384	total: 1.65s	remaining: 21.6s
71:	learn: 0.0026248	total: 1.67s	remaining: 21.5s
72:	learn: 0.0026002	total: 1.68s	remaining: 21.4s
73:	learn: 0.0025673	total: 1.7s	remaining: 21.3s
74:	learn: 0.0025546	total: 1.72s	remaining: 21.2s
75:	learn: 0.0025387	total: 1.73s	remaining: 21.1s
76:	learn: 0.0025327	total: 1.74s	remaining: 20.9s
77:	learn: 0.0025185	total: 1.76s	remaining: 20.8s
78:	learn: 0.0025128	total: 1.77s	remaining: 20.6s
79:	learn: 0.0024970	total: 1.79s	remaining: 20.5s
80:	learn: 0.0024893	total: 1.8s	remaining: 20.4s
81:	learn: 0.0024832	total: 1.82s	remaining: 20.4s
82:	learn: 0.0024691	total: 1.84s	remaining: 20.3s
83:	learn: 0.0024634	total: 1.85s	remaining: 20.2s
84:	learn: 0.0024510	total: 1.87s	remaining: 20.1s
85:	learn: 0.0024466	total: 1.89s	remaining: 20s
86:	learn: 0.0024343	total: 1.9s	remaining: 20s
87:	learn: 0.0024084	total: 1.92s	remaining: 19.9s
88:	learn: 0.0023979	total: 1.94s	remaining: 19.8s
89:	learn: 0.0023937	total: 1.95s	remaining: 19.8s
90:	learn: 0.0023839	total: 1.97s	remaining: 19.7s
91:	learn: 0.0023617	total: 1.98s	remaining: 19.6s
92:	learn: 0.0023536	total: 2s	remaining: 19.5s
93:	learn: 0.0023440	total: 2.01s	remaining: 19.4s
94:	learn: 0.0023340	total: 2.03s	remaining: 19.3s
95:	learn: 0.0023080	total: 2.04s	remaining: 19.3s
96:	learn: 0.0023038	total: 2.06s	remaining: 19.2s
97:	learn: 0.0022989	total: 2.07s	remaining: 19.1s
98:	learn: 0.0022768	total: 2.1s	remaining: 19.1s
99:	learn: 0.0022658	total: 2.12s	remaining: 19.1s
100:	learn: 0.0022415	total: 2.14s	remaining: 19.1s
101:	learn: 0.0022255	total: 2.16s	remaining: 19s
102:	learn: 0.0022186	total: 2.18s	remaining: 19s
103:	learn: 0.0021991	total: 2.19s	remaining: 18.9s
104:	learn: 0.0021909	total: 2.21s	remaining: 18.9s
105:	learn: 0.0021839	total: 2.23s	remaining: 18.8s
106:	learn: 0.0021726	total: 2.25s	remaining: 18.8s
107:	learn: 0.0021672	total: 2.27s	remaining: 18.7s
108:	learn: 0.0021602	total: 2.28s	remaining: 18.6s
109:	learn: 0.0021473	total: 2.3s	remaining: 18.6s
110:	learn: 0.0021377	total: 2.31s	remaining: 18.5s
111:	learn: 0.0021330	total: 2.33s	remaining: 18.4s
112:	learn: 0.0021281	total: 2.34s	remaining: 18.4s
113:	learn: 0.0021227	total: 2.36s	remaining: 18.3s
114:	learn: 0.0021174	total: 2.37s	remaining: 18.2s
115:	learn: 0.0021124	total: 2.39s	remaining: 18.2s
116:	learn: 0.0020937	total: 2.4s	remaining: 18.2s
117:	learn: 0.0020843	total: 2.42s	remaining: 18.1s
118:	learn: 0.0020793	total: 2.43s	remaining: 18s
119:	learn: 0.0020716	total: 2.45s	remaining: 18s
120:	learn: 0.0020624	total: 2.46s	remaining: 17.9s
121:	learn: 0.0020585	total: 2.48s	remaining: 17.8s
122:	learn: 0.0020429	total: 2.49s	remaining: 17.8s
123:	learn: 0.0020348	total: 2.51s	remaining: 17.7s
124:	learn: 0.0020280	total: 2.52s	remaining: 17.7s
125:	learn: 0.0020016	total: 2.54s	remaining: 17.6s
126:	learn: 0.0019806	total: 2.56s	remaining: 17.6s
127:	learn: 0.0019706	total: 2.57s	remaining: 17.5s
128:	learn: 0.0019452	total: 2.59s	remaining: 17.5s
129:	learn: 0.0019368	total: 2.61s	remaining: 17.5s
130:	learn: 0.0019189	total: 2.63s	remaining: 17.4s
131:	learn: 0.0019142	total: 2.64s	remaining: 17.4s
132:	learn: 0.0018942	total: 2.65s	remaining: 17.3s
133:	learn: 0.0018548	total: 2.67s	remaining: 17.3s
134:	learn: 0.0018475	total: 2.69s	remaining: 17.2s
135:	learn: 0.0018439	total: 2.7s	remaining: 17.2s
136:	learn: 0.0018284	total: 2.72s	remaining: 17.1s
137:	learn: 0.0018138	total: 2.73s	remaining: 17.1s
138:	learn: 0.0018089	total: 2.75s	remaining: 17s
139:	learn: 0.0017969	total: 2.77s	remaining: 17s
140:	learn: 0.0017932	total: 2.78s	remaining: 17s
141:	learn: 0.0017840	total: 2.8s	remaining: 16.9s
142:	learn: 0.0017713	total: 2.81s	remaining: 16.9s
143:	learn: 0.0017692	total: 2.83s	remaining: 16.8s
144:	learn: 0.0017450	total: 2.85s	remaining: 16.8s
145:	learn: 0.0017398	total: 2.87s	remaining: 16.8s
146:	learn: 0.0017368	total: 2.89s	remaining: 16.8s
147:	learn: 0.0017319	total: 2.9s	remaining: 16.7s
148:	learn: 0.0017209	total: 2.92s	remaining: 16.7s
149:	learn: 0.0016906	total: 2.94s	remaining: 16.7s
150:	learn: 0.0016879	total: 2.96s	remaining: 16.6s
151:	learn: 0.0016816	total: 2.98s	remaining: 16.6s
152:	learn: 0.0016791	total: 3.01s	remaining: 16.7s
153:	learn: 0.0016717	total: 3.03s	remaining: 16.6s
154:	learn: 0.0016641	total: 3.05s	remaining: 16.6s
155:	learn: 0.0016527	total: 3.07s	remaining: 16.6s
156:	learn: 0.0016480	total: 3.09s	remaining: 16.6s
157:	learn: 0.0016467	total: 3.11s	remaining: 16.6s
158:	learn: 0.0016434	total: 3.14s	remaining: 16.6s
159:	learn: 0.0016409	total: 3.16s	remaining: 16.6s
160:	learn: 0.0016310	total: 3.18s	remaining: 16.6s
161:	learn: 0.0016052	total: 3.19s	remaining: 16.5s
162:	learn: 0.0015898	total: 3.21s	remaining: 16.5s
163:	learn: 0.0015789	total: 3.23s	remaining: 16.4s
164:	learn: 0.0015751	total: 3.24s	remaining: 16.4s
165:	learn: 0.0015697	total: 3.26s	remaining: 16.4s
166:	learn: 0.0015659	total: 3.27s	remaining: 16.3s
167:	learn: 0.0015639	total: 3.29s	remaining: 16.3s
168:	learn: 0.0015431	total: 3.32s	remaining: 16.3s
169:	learn: 0.0015298	total: 3.34s	remaining: 16.3s
170:	learn: 0.0015267	total: 3.36s	remaining: 16.3s
171:	learn: 0.0015137	total: 3.38s	remaining: 16.3s
172:	learn: 0.0015111	total: 3.4s	remaining: 16.3s
173:	learn: 0.0015097	total: 3.42s	remaining: 16.2s
174:	learn: 0.0015088	total: 3.44s	remaining: 16.2s
175:	learn: 0.0015075	total: 3.46s	remaining: 16.2s
176:	learn: 0.0015042	total: 3.48s	remaining: 16.2s
177:	learn: 0.0015036	total: 3.5s	remaining: 16.2s
178:	learn: 0.0015020	total: 3.52s	remaining: 16.1s
179:	learn: 0.0014903	total: 3.54s	remaining: 16.1s
180:	learn: 0.0014899	total: 3.56s	remaining: 16.1s
181:	learn: 0.0014895	total: 3.58s	remaining: 16.1s
182:	learn: 0.0014767	total: 3.6s	remaining: 16.1s
183:	learn: 0.0014751	total: 3.62s	remaining: 16s
184:	learn: 0.0014722	total: 3.63s	remaining: 16s
185:	learn: 0.0014649	total: 3.66s	remaining: 16s
186:	learn: 0.0014632	total: 3.68s	remaining: 16s
187:	learn: 0.0014624	total: 3.7s	remaining: 16s
188:	learn: 0.0014496	total: 3.72s	remaining: 15.9s
189:	learn: 0.0014486	total: 3.73s	remaining: 15.9s
190:	learn: 0.0014461	total: 3.76s	remaining: 15.9s
191:	learn: 0.0014434	total: 3.78s	remaining: 15.9s
192:	learn: 0.0014428	total: 3.8s	remaining: 15.9s
193:	learn: 0.0014346	total: 3.81s	remaining: 15.8s
194:	learn: 0.0014270	total: 3.83s	remaining: 15.8s
195:	learn: 0.0014268	total: 3.85s	remaining: 15.8s
196:	learn: 0.0014261	total: 3.86s	remaining: 15.7s
197:	learn: 0.0014225	total: 3.88s	remaining: 15.7s
198:	learn: 0.0014145	total: 3.9s	remaining: 15.7s
199:	learn: 0.0014015	total: 3.92s	remaining: 15.7s
200:	learn: 0.0013984	total: 3.94s	remaining: 15.6s
201:	learn: 0.0013972	total: 3.96s	remaining: 15.6s
202:	learn: 0.0013903	total: 3.98s	remaining: 15.6s
203:	learn: 0.0013770	total: 4s	remaining: 15.6s
204:	learn: 0.0013653	total: 4.02s	remaining: 15.6s
205:	learn: 0.0013631	total: 4.04s	remaining: 15.6s
206:	learn: 0.0013541	total: 4.06s	remaining: 15.5s
207:	learn: 0.0013521	total: 4.08s	remaining: 15.5s
208:	learn: 0.0013511	total: 4.09s	remaining: 15.5s
209:	learn: 0.0013498	total: 4.11s	remaining: 15.5s
210:	learn: 0.0013491	total: 4.13s	remaining: 15.4s
211:	learn: 0.0013483	total: 4.15s	remaining: 15.4s
212:	learn: 0.0013472	total: 4.17s	remaining: 15.4s
213:	learn: 0.0013471	total: 4.19s	remaining: 15.4s
214:	learn: 0.0013377	total: 4.21s	remaining: 15.4s
215:	learn: 0.0013310	total: 4.22s	remaining: 15.3s
216:	learn: 0.0013303	total: 4.24s	remaining: 15.3s
217:	learn: 0.0013302	total: 4.3s	remaining: 15.4s
218:	learn: 0.0013186	total: 4.32s	remaining: 15.4s
219:	learn: 0.0013174	total: 4.37s	remaining: 15.5s
220:	learn: 0.0013073	total: 4.39s	remaining: 15.5s
221:	learn: 0.0013063	total: 4.43s	remaining: 15.5s
222:	learn: 0.0013050	total: 4.46s	remaining: 15.5s
223:	learn: 0.0012961	total: 4.48s	remaining: 15.5s
224:	learn: 0.0012944	total: 4.53s	remaining: 15.6s
225:	learn: 0.0012864	total: 4.56s	remaining: 15.6s
226:	learn: 0.0012846	total: 4.6s	remaining: 15.7s
227:	learn: 0.0012842	total: 4.63s	remaining: 15.7s
228:	learn: 0.0012829	total: 4.67s	remaining: 15.7s
229:	learn: 0.0012828	total: 4.7s	remaining: 15.7s
230:	learn: 0.0012823	total: 4.74s	remaining: 15.8s
231:	learn: 0.0012790	total: 4.77s	remaining: 15.8s
232:	learn: 0.0012780	total: 4.8s	remaining: 15.8s
233:	learn: 0.0012771	total: 4.83s	remaining: 15.8s
234:	learn: 0.0012763	total: 4.85s	remaining: 15.8s
235:	learn: 0.0012739	total: 4.89s	remaining: 15.8s
236:	learn: 0.0012731	total: 4.91s	remaining: 15.8s
237:	learn: 0.0012724	total: 4.92s	remaining: 15.8s
238:	learn: 0.0012721	total: 4.93s	remaining: 15.7s
239:	learn: 0.0012711	total: 4.95s	remaining: 15.7s
240:	learn: 0.0012708	total: 4.96s	remaining: 15.6s
241:	learn: 0.0012699	total: 4.97s	remaining: 15.6s
242:	learn: 0.0012694	total: 4.99s	remaining: 15.5s
243:	learn: 0.0012689	total: 5.01s	remaining: 15.5s
244:	learn: 0.0012616	total: 5.02s	remaining: 15.5s
245:	learn: 0.0012577	total: 5.03s	remaining: 15.4s
246:	learn: 0.0012574	total: 5.05s	remaining: 15.4s
247:	learn: 0.0012567	total: 5.07s	remaining: 15.4s
248:	learn: 0.0012551	total: 5.09s	remaining: 15.4s
249:	learn: 0.0012523	total: 5.1s	remaining: 15.3s
250:	learn: 0.0012454	total: 5.12s	remaining: 15.3s
251:	learn: 0.0012440	total: 5.14s	remaining: 15.2s
252:	learn: 0.0012437	total: 5.15s	remaining: 15.2s
253:	learn: 0.0012434	total: 5.16s	remaining: 15.2s
254:	learn: 0.0012430	total: 5.18s	remaining: 15.1s
255:	learn: 0.0012428	total: 5.2s	remaining: 15.1s
256:	learn: 0.0012423	total: 5.21s	remaining: 15.1s
257:	learn: 0.0012420	total: 5.24s	remaining: 15.1s
258:	learn: 0.0012392	total: 5.26s	remaining: 15s
259:	learn: 0.0012371	total: 5.28s	remaining: 15s
260:	learn: 0.0012364	total: 5.3s	remaining: 15s
261:	learn: 0.0012273	total: 5.32s	remaining: 15s
262:	learn: 0.0012264	total: 5.34s	remaining: 15s
263:	learn: 0.0012234	total: 5.35s	remaining: 14.9s
264:	learn: 0.0012232	total: 5.37s	remaining: 14.9s
265:	learn: 0.0012208	total: 5.39s	remaining: 14.9s
266:	learn: 0.0012184	total: 5.41s	remaining: 14.8s
267:	learn: 0.0012172	total: 5.42s	remaining: 14.8s
268:	learn: 0.0012165	total: 5.44s	remaining: 14.8s
269:	learn: 0.0012069	total: 5.45s	remaining: 14.7s
270:	learn: 0.0012061	total: 5.47s	remaining: 14.7s
271:	learn: 0.0012061	total: 5.49s	remaining: 14.7s
272:	learn: 0.0012060	total: 5.51s	remaining: 14.7s
273:	learn: 0.0012050	total: 5.53s	remaining: 14.6s
274:	learn: 0.0012050	total: 5.55s	remaining: 14.6s
275:	learn: 0.0012003	total: 5.56s	remaining: 14.6s
276:	learn: 0.0011992	total: 5.58s	remaining: 14.6s
277:	learn: 0.0011985	total: 5.6s	remaining: 14.5s
278:	learn: 0.0011981	total: 5.62s	remaining: 14.5s
279:	learn: 0.0011973	total: 5.64s	remaining: 14.5s
280:	learn: 0.0011945	total: 5.65s	remaining: 14.5s
281:	learn: 0.0011910	total: 5.67s	remaining: 14.4s
282:	learn: 0.0011891	total: 5.69s	remaining: 14.4s
283:	learn: 0.0011886	total: 5.71s	remaining: 14.4s
284:	learn: 0.0011877	total: 5.73s	remaining: 14.4s
285:	learn: 0.0011871	total: 5.74s	remaining: 14.3s
286:	learn: 0.0011861	total: 5.76s	remaining: 14.3s
287:	learn: 0.0011848	total: 5.79s	remaining: 14.3s
288:	learn: 0.0011842	total: 5.8s	remaining: 14.3s
289:	learn: 0.0011749	total: 5.82s	remaining: 14.3s
290:	learn: 0.0011685	total: 5.84s	remaining: 14.2s
291:	learn: 0.0011667	total: 5.86s	remaining: 14.2s
292:	learn: 0.0011656	total: 5.88s	remaining: 14.2s
293:	learn: 0.0011610	total: 5.89s	remaining: 14.2s
294:	learn: 0.0011603	total: 5.91s	remaining: 14.1s
295:	learn: 0.0011603	total: 5.93s	remaining: 14.1s
296:	learn: 0.0011601	total: 5.95s	remaining: 14.1s
297:	learn: 0.0011596	total: 5.96s	remaining: 14.1s
298:	learn: 0.0011593	total: 5.98s	remaining: 14s
299:	learn: 0.0011585	total: 6s	remaining: 14s
300:	learn: 0.0011570	total: 6.02s	remaining: 14s
301:	learn: 0.0011519	total: 6.04s	remaining: 14s
302:	learn: 0.0011466	total: 6.06s	remaining: 13.9s
303:	learn: 0.0011458	total: 6.07s	remaining: 13.9s
304:	learn: 0.0011458	total: 6.09s	remaining: 13.9s
305:	learn: 0.0011410	total: 6.11s	remaining: 13.9s
306:	learn: 0.0011385	total: 6.14s	remaining: 13.9s
307:	learn: 0.0011384	total: 6.15s	remaining: 13.8s
308:	learn: 0.0011383	total: 6.17s	remaining: 13.8s
309:	learn: 0.0011344	total: 6.19s	remaining: 13.8s
310:	learn: 0.0011277	total: 6.21s	remaining: 13.8s
311:	learn: 0.0011271	total: 6.22s	remaining: 13.7s
312:	learn: 0.0011229	total: 6.24s	remaining: 13.7s
313:	learn: 0.0011191	total: 6.26s	remaining: 13.7s
314:	learn: 0.0011168	total: 6.28s	remaining: 13.7s
315:	learn: 0.0011113	total: 6.31s	remaining: 13.7s
316:	learn: 0.0011055	total: 6.33s	remaining: 13.6s
317:	learn: 0.0011048	total: 6.35s	remaining: 13.6s
318:	learn: 0.0011046	total: 6.37s	remaining: 13.6s
319:	learn: 0.0011044	total: 6.38s	remaining: 13.6s
320:	learn: 0.0011042	total: 6.4s	remaining: 13.5s
321:	learn: 0.0010987	total: 6.42s	remaining: 13.5s
322:	learn: 0.0010984	total: 6.44s	remaining: 13.5s
323:	learn: 0.0010979	total: 6.45s	remaining: 13.5s
324:	learn: 0.0010977	total: 6.47s	remaining: 13.4s
325:	learn: 0.0010969	total: 6.49s	remaining: 13.4s
326:	learn: 0.0010939	total: 6.5s	remaining: 13.4s
327:	learn: 0.0010909	total: 6.53s	remaining: 13.4s
328:	learn: 0.0010839	total: 6.54s	remaining: 13.3s
329:	learn: 0.0010817	total: 6.56s	remaining: 13.3s
330:	learn: 0.0010806	total: 6.58s	remaining: 13.3s
331:	learn: 0.0010804	total: 6.6s	remaining: 13.3s
332:	learn: 0.0010799	total: 6.62s	remaining: 13.3s
333:	learn: 0.0010797	total: 6.64s	remaining: 13.2s
334:	learn: 0.0010791	total: 6.65s	remaining: 13.2s
335:	learn: 0.0010781	total: 6.67s	remaining: 13.2s
336:	learn: 0.0010781	total: 6.69s	remaining: 13.2s
337:	learn: 0.0010755	total: 6.71s	remaining: 13.1s
338:	learn: 0.0010736	total: 6.73s	remaining: 13.1s
339:	learn: 0.0010667	total: 6.75s	remaining: 13.1s
340:	learn: 0.0010630	total: 6.77s	remaining: 13.1s
341:	learn: 0.0010581	total: 6.79s	remaining: 13.1s
342:	learn: 0.0010558	total: 6.81s	remaining: 13.1s
343:	learn: 0.0010500	total: 6.84s	remaining: 13s
344:	learn: 0.0010496	total: 6.86s	remaining: 13s
345:	learn: 0.0010476	total: 6.87s	remaining: 13s
346:	learn: 0.0010476	total: 6.89s	remaining: 13s
347:	learn: 0.0010473	total: 6.91s	remaining: 12.9s
348:	learn: 0.0010471	total: 6.93s	remaining: 12.9s
349:	learn: 0.0010451	total: 6.94s	remaining: 12.9s
350:	learn: 0.0010448	total: 6.96s	remaining: 12.9s
351:	learn: 0.0010445	total: 6.99s	remaining: 12.9s
352:	learn: 0.0010440	total: 7s	remaining: 12.8s
353:	learn: 0.0010434	total: 7.02s	remaining: 12.8s
354:	learn: 0.0010433	total: 7.05s	remaining: 12.8s
355:	learn: 0.0010386	total: 7.07s	remaining: 12.8s
356:	learn: 0.0010344	total: 7.09s	remaining: 12.8s
357:	learn: 0.0010342	total: 7.12s	remaining: 12.8s
358:	learn: 0.0010339	total: 7.14s	remaining: 12.8s
359:	learn: 0.0010329	total: 7.16s	remaining: 12.7s
360:	learn: 0.0010328	total: 7.18s	remaining: 12.7s
361:	learn: 0.0010327	total: 7.2s	remaining: 12.7s
362:	learn: 0.0010325	total: 7.22s	remaining: 12.7s
363:	learn: 0.0010321	total: 7.23s	remaining: 12.6s
364:	learn: 0.0010316	total: 7.25s	remaining: 12.6s
365:	learn: 0.0010298	total: 7.26s	remaining: 12.6s
366:	learn: 0.0010297	total: 7.28s	remaining: 12.6s
367:	learn: 0.0010295	total: 7.29s	remaining: 12.5s
368:	learn: 0.0010242	total: 7.31s	remaining: 12.5s
369:	learn: 0.0010234	total: 7.32s	remaining: 12.5s
370:	learn: 0.0010233	total: 7.34s	remaining: 12.5s
371:	learn: 0.0010202	total: 7.36s	remaining: 12.4s
372:	learn: 0.0010201	total: 7.38s	remaining: 12.4s
373:	learn: 0.0010159	total: 7.39s	remaining: 12.4s
374:	learn: 0.0010141	total: 7.41s	remaining: 12.4s
375:	learn: 0.0010140	total: 7.43s	remaining: 12.3s
376:	learn: 0.0010137	total: 7.44s	remaining: 12.3s
377:	learn: 0.0010131	total: 7.45s	remaining: 12.3s
378:	learn: 0.0010129	total: 7.47s	remaining: 12.2s
379:	learn: 0.0010094	total: 7.48s	remaining: 12.2s
380:	learn: 0.0010089	total: 7.5s	remaining: 12.2s
381:	learn: 0.0010089	total: 7.51s	remaining: 12.2s
382:	learn: 0.0010066	total: 7.53s	remaining: 12.1s
383:	learn: 0.0010039	total: 7.55s	remaining: 12.1s
384:	learn: 0.0010025	total: 7.56s	remaining: 12.1s
385:	learn: 0.0010016	total: 7.58s	remaining: 12.1s
386:	learn: 0.0010016	total: 7.59s	remaining: 12s
387:	learn: 0.0010012	total: 7.61s	remaining: 12s

ValueError: Classification metrics can't handle a mix of binary and continuous targets